name: forms-flow-admin-CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - main-rsbc
      - develop
    paths:
      - "forms-flow-admin/**"

jobs:
  ci:
    uses: ./.github/workflows/ci-workflow.yml
    with:
      working_directory: ./forms-flow-admin
      node_version: '24.x'
      enable_lint: false
      enable_test: false
      enable_build: true

