name: Push Forms flow Microfrontend to registry

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main-rsbc
      - develop

defaults:
  run:
    shell: bash

jobs:
  build-and-push-image-to-artifactory:
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: ./.github/workflows/cd-workflow.yml
    with:
      DOCKER_CONTEXT: .
      DOCKER_FILE: Dockerfile
      DOCKER_IMAGE_NAME: formsflow/forms-flow-microfrontend
    secrets: inherit
